name: QCLab

on:
  push:
    branches:
      - main
    paths:
      - 'modelos/**'
      - 'treinamento/**'
      - 'app.py'
      - 'requirements.txt'
      - 'Dockerfile'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Instalar dependências Python
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Treinar modelo
        run: python treinamento/treina_modelo.py

      - name: Login no Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagem Docker com novo modelo
        run: docker build -t qc-app:latest .

      - name: Validar manifestos Kubernetes
        uses: stefanprodan/kube-tools@v1
        with:
          command: kubeconform -summary -strict k8s/
